In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [9]:
data =pd.read_csv('dummy_data.csv')

In [10]:
data

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car
0,56,male,3,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774,True,False,False
1,46,female,2,Facebook,Travel,United Kingdom,Urban,Student,10564,True,True,True
2,32,male,8,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258,False,False,False
3,60,non-binary,5,Instagram,Travel,United Kingdom,Urban,Student,12500,False,True,False
4,25,male,1,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536,False,True,False
996,40,non-binary,6,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711,True,False,False
997,27,non-binary,5,YouTube,Travel,United Kingdom,Rural,Student,17595,True,False,True
998,61,female,4,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273,True,True,False
999,19,female,8,YouTube,Travel,Australia,Rural,Student,16284,False,True,False

In [11]:
le = LabelEncoder()
data['PltEncoder'] = le.fit_transform(data['platform'])

In [12]:
data

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,PltEncoder
0,56,male,3,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774,True,False,False,1
1,46,female,2,Facebook,Travel,United Kingdom,Urban,Student,10564,True,True,True,0
2,32,male,8,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258,False,False,False,1
3,60,non-binary,5,Instagram,Travel,United Kingdom,Urban,Student,12500,False,True,False,1
4,25,male,1,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566,False,True,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536,False,True,False,1
996,40,non-binary,6,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711,True,False,False,2
997,27,non-binary,5,YouTube,Travel,United Kingdom,Rural,Student,17595,True,False,True,2
998,61,female,4,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273,True,True,False,2
999,19,female,8,YouTube,Travel,Australia,Rural,Student,16284,False,True,False,2

In [13]:
X = data[['time_spent']]
y = data['PltEncoder']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [16]:
y_pred = model.predict(X_test)

In [17]:
print(y_pred)

[1 1 2 1 2 2 2 2 1 1 1 1 2 2 1 1 2 2 1 1 1 1 2 1 1 2 1 2 1 1 2 2 1 1 2 1 1
 1 1 1 2 1 1 1 2 1 2 2 1 1 1 1 1 1 2 2 1 1 2 1 1 1 1 1 1 1 1 2 2 1 2 2 1 1
 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1 2 1 1 1 1 1 2 1 1 2 1 2 1 1 2 1 1 2 1
 1 2 2 1 1 2 1 1 1 1 1 1 2 2 1 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 1
 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 1 2 2 1 1 1 2 1 1 1 2 1 1 2 1 1 1
 1 1 2 2 1 1 1 1 1 1 2 1 2 1 1]

In [19]:
a = accuracy_score(y_test, y_pred)
cm= confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)

C:\Users\asus\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\asus\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\asus\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [39]:
a

0.355

In [40]:
cm

array([[ 0, 45, 12],
       [ 0, 49, 25],
       [ 0, 47, 22]], dtype=int64)

In [41]:
cr

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        57\n           1       0.35      0.66      0.46        74\n           2       0.37      0.32      0.34        69\n\n    accuracy                           0.36       200\n   macro avg       0.24      0.33      0.27       200\nweighted avg       0.26      0.35      0.29       200\n'